server:
  port: 8082

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: payment-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.rishit.common.event.OrderCreateEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.springframework.kafka: INFO

eureka:

  instance:
    hostname: localhost
    prefer-ip-address: true

  client:

    service-url:

      defaultZone: http://localhost:8761/eureka/

management:

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080


spring:

  application:
    name: api-gateway


  cloud:

    gateway:

      server:

        webmvc:

          routes:

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**


            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**


            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/inventory/**


eureka:

  instance:
    hostname: localhost
    prefer-ip-address: true

  client:

    service-url:

      defaultZone: http://localhost:8761/eureka/

management:

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: "*"

logging:

  pattern:

    level: "%5p [%X{traceId:-},%X{spanId:-}]"
